name: 'auto merge deps'

on:
  pull_request_target:
    types: [labeled]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run:
    name: auto merge deps
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'auto-update-deps')
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Echo PR information
        run: |
          echo "[info] PR number: ${{ github.event.pull_request.number }}"
          echo "[info] PR title: ${{ github.event.pull_request.title }}"

      - name: Check PR context
        id: check
        run: |
          gh pr checkout "${{ github.event.pull_request.number }}"
          echo "${{ github.event.pull_request.title }}" | \
          sed -e "s/^chore.*: \(.*\)/\1/" | \
          sed -e "s/^/chore(deps): ⬆️ /" | \
          xargs echo "::set-output name=title::$1"
          git log --pretty=format:"%b" -1 | \
          xargs echo "::set-output name=body::$1"

      - name: Enhance PR title
        env:
          number: ${{ github.event.pull_request.number }}
          title: ${{ steps.check.outputs.title }}
        run: |
          gh pr edit ${{ env.number }} --title "${{ env.title }}"

      - name: Auto merge dependabot PR
        env:
          number: ${{ github.event.pull_request.number }}
          title: ${{ steps.check.outputs.title }}
          body: ${{ steps.check.outputs.title }}
        run: |
          gh pr merge ${{ env.number }} -s "${{ env.title }}" -b "${{ env.title }}"